export const GET_ROOMS_REQUEST = 'GET_ROOMS_REQUEST';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_ERROR = 'GET_ROOMS_ERROR';
export const SET_FLOORS = 'SET_FLOORS';
export const SET_ROOMS = 'SET_ROOMS';

export const POST_EVENT_REQUEST = 'POST_EVENT_REQUEST';
export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
export const POST_EVENT_ERROR = 'POST_EVENT_ERROR';
export const DELETE_EVENT = 'DELETE_EVENT';
export const SET_ACTIVE_EVENT = 'SET_ACTIVE_EVENT';
export const SHOW_MESSAGE_CREATED_EVENT = 'SHOW_MESSAGE_CREATED_EVENT';
export const HIDE_MESSAGE_CREATED_EVENT = 'HIDE_MESSAGE_CREATED_EVENT';

export const GET_DIAGRAM_DATA = 'GET_DIAGRAM_DATA';

export const SHOW_TOOLTIP = 'SHOW_TOOLTIP';
export const HIDE_TOOLTIP = 'HIDE_TOOLTIP';
export const SET_TOOLTIP_COORD = 'SET_TOOLTIP_COORD';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';


export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';
export const SET_EVENTS = 'SET_EVENTS';

export const SET_DATE = 'SET_DATE';

export const UPDATE_CURRENT_TIME = 'UPDATE_CURRENT_TIME'; 

export const OPEN_HOME_PAGE = 'OPEN_HOME_PAGE';
export const OPEN_CHANGE_EVENT_PAGE = 'OPEN_CHANGE_EVENT_PAGE';
export const OPEN_NEW_EVENT_PAGE = 'OPEN_NEW_EVENT_PAGE';
